### PR TITLE
Fix description of Code with Scope

### PR DESCRIPTION
**Pull request by ajdavis**

### CODE REVIEW

**Comment by ajdavis** [comment]
@kevinalbs could you review this please?

**Comment by kevinAlbs** [comment]
lgtm

**Comment by kevinAlbs** [comment]
Wait... I misread "string" for "cstring" in the spec, and I now think the original comment was correct. The rule for "string" itself has a int32 accounting for the null char. So the int32 is for the string + doc length. I did a sanity check here: https://gist.github.com/kevinAlbs/4467755ef5694de9c3ff43cf40f8bc60

**Comment by ajdavis** [comment]
Yes, I made a related mistake, thanks.

**Pull request closed without merging**
